<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="3" time="0.081" timestamp="2024-02-27T22:37:17.140645" hostname="DiegoSebastian"><testcase classname="test_deadants.TestAntsFunction" name="test_ants1" file="test_deadants.py" line="4" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_deadants.TestAntsFunction" name="test_ants2" file="test_deadants.py" line="8" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_deadants.TestAntsFunction" name="test_ants3" file="test_deadants.py" line="20" time="0.001"><failure message="AssertionError: 9 != 10">self = &lt;test_deadants.TestAntsFunction testMethod=test_ants3&gt;

    def test_ants3(self):
        ants_problem = ".n..tt.n.nt..t.ntant..aaaaa..tn.na.aaat..n..tn.ntan.t"
&gt;       self.assertEqual(antsfunction(ants_problem), 10)
E       AssertionError: 9 != 10

test_deadants.py:23: AssertionError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>